apiVersion: apps/v1
kind: Deployment
metadata:
  name: micro2
  namespace: dev
  labels:
    app: micro2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: micro2
  template:
    metadata:
      labels:
        app: micro2
    spec:
      containers:
      - name: micro2
        image: micros1lite.azurecr.io/micro1:3.0 
        env:
        - name: CODIGO
          valueFrom: 
           configMapKeyRef:
             name: micro2
             key: CODIGO
        ports:
        - containerPort: 8080

 
