apiVersion: apps/v1
kind: Deployment
metadata:
  name: micro3
  namespace: dev
  labels:
    app: micro3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: micro3
  template:
    metadata:
      labels:
        app: micro3
    spec:
      containers:
      - name: micro3
        image: mauron/demo:17
        env:
        - name: CODIGO
          valueFrom: 
           configMapKeyRef:
             name: micro3
             key: CODIGO
        ports:
        - containerPort: 8080

 
