apiVersion: v1
kind: Service
metadata:
  name: micro3
  namespace: dev
spec:
  type: LoadBalancer 
  selector:
    app: micro3
  ports:
    - name: http
      protocol: TCP
      port: 8888
      targetPort: 8080
